title: Christina Bharara # your name (or website title) here
logo: "/images/christina_bharara_profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mobile App Developer 
  <br><br>
  I create mobile apps, using React Native, Xcode, Android Studio and sometimes Unity. 
  <br><br>
  <a href="https://www.linkedin.com/in/cabhara/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
