title: Christina Bharara # your name (or website title) here
logo: "/images/christina_bharara_profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mobile App Developer 
  <br><br>
  I create mobile apps, using React Native, Xcode, Android Studio and sometimes Unity. 
  <br><br>
  <a href="https://www.linkedin.com/in/cabhara/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://apps.apple.com/us/developer/christina-bharara/id325350531">My personal iOS apps</a>
  <br><br>
  <a href="https://play.google.com/store/apps/dev?id=6063180645200960818">My personal Android apps</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
